print(f'True e True é {True and True}')
print(f'True e False é {True and False}')
print(f'False e False é {False and False}')
print()
print(f'True ou True é {True or True}')
print(f'True ou False é {True or False}')
print(f'False ou False é {False or False}')
print()
print(f'not True é {not True}')
print(f'not False é {not True}')