print('Comparação (igual) 5 == 5', 5==5)
print('Comparação (diferente) 3 != 5', 3!=5)
print('Comparação (maior que) 3 > 5', 3>5)
print('Comparação (menor que) 3 < 5', 3<5)
print('Comparação (maior ou igual que) 3 >= 3', 3 >= 3)
print('Comparação (menor ou igual que) 3 <= 3', 3<= 3)